---

# Not sure if necessary
- name: Get os specific facts
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Install packages
  ansible.builtin.package:
    name: potos_packages
    state: latest
  when: potos_packages is defined and
        potos_packages is not string and
        (potos_packages | length > 0)
