---

- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    potos_packages:
      - nix
  tasks:
    - name: run role
      ansible.builtin.include_role:
        name: 'ansible-role-potos_packages'
