---

- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    potos_wallpaper_images:
      - "potos-wallpaper_test.png"
  tasks:
    - name: run role
      ansible.builtin.include_role:
        name: 'ansible-role-potos_wallpaper'
